### PR TITLE
Change to Wide Mode

### PR DESCRIPTION
**Pull request by abrieff**
Use full screen to display reports. May require some updates as we go to get the formatting exactly how we like
Screen Shot 2022-07-25 at 1 18 25 PM
Screen Shot 2022-07-25 at 1 24 18 PM

### CODE REVIEW

**Review by mbh329 — APPROVED** [review]

**Comment by SashaWeinstein** [comment]
Reviewing each page

**Comment by SashaWeinstein** [comment]
Overall I think the pages look better. I found a couple places where the change makes elements look worse
### Pluto Page
- The graphs aren't quite in the center of the page
- The tables in the outlier report have empty white space to right

### FacDB Page
- Table for change in total number of records is too far to the left, looks odd. 

Can help address any of these issues on this branch or a feature branch that is branched of `95-change-to-wide-mode`

**Review by SashaWeinstein — CHANGES_REQUESTED** [review]
I like the change overall, there are couple places where it has a negative impact on the layout in my opinion. I wrote up the problems I saw in a comment

**Comment by mbh329** [comment]
I hastily approved this PR so my apologies for not taking a better look at this. 

PLUTO
The white space to the right of the outlier reports doesn't bother me all that much but the different size of each graph and them not being centered does. Would be nice if we can align and standardize the size better. I feel like the white space issues is a nice to have so if it is a real pain than maybe we can just leave it (?)

FacDB
Would be nice to have it centered, the viewer does have the option to expand the column width by dragging it out which makes it a little less annoying.

**Comment by abrieff** [comment]
Makes sense - I don't think it's worth putting all of the effort into now - will shelve and maybe pick up with free time

**Pull request closed without merging**
