### PR TITLE
check whether all projects fall within nyc borough boundaries

### PR DESCRIPTION
**Pull request by Oysters1874**

### CODE REVIEW

**Comment by Oysters1874** [comment]
I feel like I am adding more complexities into the table reading part, not sure how to make it look better.

**Comment by td928** [comment]
Hey @Oysters1874 understand your comments about it. To be fair, it was designed with quite a bit complexity by me. I think you did a good job to make it accommodating your work. I think we can talk about how to make this how process more streamlined at another time. 

I do have some comments about the spatial check file itself. When I run the geospatial check locally on my machine, I don't think I had an empty dataframe at the end meaning some records are not within the NYC boundary. I am wondering what are you seeing when you run locally and if that means the github action produces the correct dataframe. I also think it might be helpful overall to use (maybe even fake data) to test out the functionality of the scenario where there is outliers.

**Comment by td928** [comment]
Iooks like the cpdb_dcpattributes_poly simply wasn't created until exporting step. Maybe use cpdb_dcpattributes should solve this issue?

**Comment by Oysters1874** [comment]
> Iooks like the cpdb_dcpattributes_poly simply wasn't created until exporting step. Maybe use cpdb_dcpattributes should solve this issue?

okay, I see the problem here. Probably need to modify on the cpdb side again.

**Comment by Oysters1874** [comment]
> > Iooks like the cpdb_dcpattributes_poly simply wasn't created until exporting step. Maybe use cpdb_dcpattributes should solve this issue?
> 
> okay, I see the problem here. Probably need to modify on the cpdb side again.

opened another pr here for this code change. (https://github.com/NYCPlanning/db-cpdb/pull/124)

**Comment by Oysters1874** [comment]
One thing that I am wondering is whether we are going to add sidebar for version selection in the future. Because the geospatial check table records all projects within one single row for each version, so far I am just selecting the last row of the table assuming the insertion of new versions will happen at the end of the csv file.

**Comment by td928** [comment]
I think the latest version makes sense but not sure taking the last row is the best design given: 1) maybe there are other query result would be dumped in the same json 2) the table should be created from scratch anyway so only the result from the current version would be in the table anyway. Let me know if you think differently

**Comment by Oysters1874** [comment]
> I think the latest version makes sense but not sure taking the last row is the best design given: 1) maybe there are other query result would be dumped in the same json 2) the table should be created from scratch anyway so only the result from the current version would be in the table anyway. Let me know if you think differently

You are right. I was thinking to fetch the existing table every time when we implement a new version of cpdb without recreating the table every time, just like what pluto has done. But later I kind of forgot about the issue, as there is no existing code seems to handle the version. If we don't need to care about version at all for cpdb, I will just make the code fetch the entire table, as the table should always contain one row.

**Comment by td928** [comment]
oh I think this should be fairly easy thing to do on your side. I switched from "component" to "components" in naming the folder. Would you mind changing it in this PR also?

**Comment by Oysters1874** [comment]
> oh I think this should be fairly easy thing to do on your side. I switched from "component" to "components" in naming the folder. Would you mind changing it in this PR also?

sure

**Comment by td928** [comment]
for some reason the `component` folder didn't get deleted after changing the name. Is the delete change no included in the commit?

**Review by td928 — APPROVED** [review]
LGTM

**Pull request merged**
