### PR TITLE
Change Popup Values in Aggregate Graph to human readable values

### PR DESCRIPTION
**Pull request by mbh329**
Addresses issue #165 

Aggregate graph popup values were being shown as sci notation, changed it to display a float as Lynn suggested. 

:star:

### CODE REVIEW

**Comment by SashaWeinstein** [comment]
Awesome, thanks for addressing this issue. I find the floats with >5 digits hard to read, which I why I switched to scientific notation. I'm wondering if there's another better way to display the big floats. There should be some fairly easy way to display numbers greater than 99,999 as "556 thousand" or "8 million". I can google around for a solution after I approve the PR I'm working on now

**Comment by Oysters1874** [comment]
I think the scientific notation actually looks fine, as it is more professional. As long as we keep them coherent, I don't feel we need to care too much about the readability of the sci notation.

**Comment by abrieff** [comment]
there's also https://www.geeksforgeeks.org/python-numerize-library/ as maybe an option?

**Comment by SashaWeinstein** [comment]
Yea numerize looks like what we want

**Comment by mbh329** [comment]
@SashaWeinstein @abrieff thanks for the suggested solution! updated to reflect your suggestion

**Review by abrieff — APPROVED** [review]
lgtm! wonder if there are other places it would be helpful

**Review by SashaWeinstein — APPROVED** [review]
Looks good to me! Like the M's, like the B's, like the K's

**Pull request merged**
